### ISSUE TITLE
Change primary photo

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#11]
This needs some discussion before implementation. The basic point is that when you upload multiple photos, the first is used as the primary image, which might not be what you want.  We need an intuitive way to change the primary photo.

**Comment by misterpekert** [comment]
@edwh there are a couple of possible solutions for that problem:

1. Put left/right arrows on each photo item to rearrange their order in the post. Visually highlight or add some label to the first one, saying it's the one which will be used as the primary. I don't think it's our option, as there are already two buttons to rotate the picture and 1 to delete. Having arrows, there might be a problem in understanding what each arrow does, and it'll be a mess with five icons on 1 photo. Also, on mobile phones, those images are in 1 column, so left/right doesn't make much sense, but it should instead be top/down 😆 
2. Remove the "rotate clockwise" button, put the "delete" icon on its spot and have a small button with text (_Use as primary_) in the middle of the bottom half of the picture. We can also add some border around the image to indicate that it's a primary one. I don't know about this from the backend point of view. Is it possible to mark specific images as "primary", or does it use the first one by default? If to set the image as primary, it needs to be the first one in the array, and then we can swap them for a user when they click the "Use as primary" button. I made a quick mark up to show what I meant.
<img width="209" alt="image" src="https://github.com/Freegle/iznik-nuxt3/assets/11361743/d7435575-4eb1-40f8-8b16-922a63a9ce74">
3. We can have a separate button to open a popup with the same images but smaller sizes and no icons. On that popup, the user could choose the primary image.


I'd go with either 2 or 3. Let me know what your thoughts on that issue are

**Comment by edwh** [comment]
I think drag and drop would be better than buttons. It's the natural UX for reordering, especially on mobile, and is less visual clutter. 

The primary image should be the first one, with a success border.

**Comment by edwh** [comment]
I'll need to add a server call, but you can do the client side.
