### ISSUE TITLE
Use `useModal` composable everywhere instead of the `modal` mixin.

### ISSUE THREAD

**Issue by smellyshovel** [Freegle/iznik-nuxt3#13]
Now we have both a composable and a mixin with the same function.  Composable is better, so we need to migrate to that in the places where we currently use the mixin.  It doesn't need to in this PR - please create another issue for that.

_Originally posted by @edwh in https://github.com/Freegle/iznik-nuxt3/pull/8#discussion_r1304332926_

**Comment by smellyshovel** [comment]
@edwh 

Regarding this one. I think there's no point in maintaining neither the useModal composable nor the respective mixin. The composable was added only for the backwards-compatibility with the existing mixin (when rewriting some other component to use the Composition API (and mixins are not available with the Composition API)). For all the modals we use the `b-modal` component which is enough self-contained by itself: it provides both the `show` and `hide` API as well as allows to toggle its visibility with the help of `v-model` directive. 

The only specific thing that `useModal` provides is that it adds some code to handle navigating back using the built-in router. I'm not sure which problems it solves, but I'm pretty much sure that that's a very rare (if not an exclusive) case which could be handled on the level of that certain modal which depends on it.

Generally speaking, I believe we should get rid of the composable whatsoever. Maybe also get rid of the mixin, but I'm afraid to break things.

What do you think?

**Comment by edwh** [comment]
The back code is because people often hit the back button when they want to close a modal. Without this, they get sent to the previous page, and then have to navigate forwards again, which causes confusion and annoyance. It's not that uncommon. 

So we always want the back button to close the modal.

If we can handle that globally, then I agree we could remove both the mixin and the composable.
