### ISSUE TITLE
Add toSorted polyfill

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#14]
We added a use of `toSorted` in `myposts`.  This broke some older browsers.  We should add a polyfill so that we don't have to remember not to use it.

**Comment by smellyshovel** [comment]
@edwh Are there any guidelines on how to add polyfills on the project level? Couldn't find anything by searching by the "polyfill" in the code.

**Comment by edwh** [comment]
We don't have anything standard.  In the past I've used polyfills from various places, usually standalone packages.  I think `core-js` has a lot.

Key thing is that it needs to be built locally, not a dynamic script which pulls it in from a site.

**Comment by smellyshovel** [comment]
I'm not sure whether this is relevant anymore. Don't see the usages of `toSorted` after some of your changes.

**Comment by smellyshovel** [comment]
What are the minimum browser requirements? Can we use automatic Core JS's polyfills?

**Comment by edwh** [comment]
We can use CoreJS if it has one, yes. 

The browser support is in vite.config.js - es2015 up. There are some oddities in the support but the overall aim is to support old kit if we can, given the purpose of the site. 

We'd support XP if we could, but Nuxt/Vue don't any more.
