### ISSUE TITLE
HEIC conversion issue

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#18]
In `OurFilePond` we convert HEIC files because the server PHP code can't cope with them.  It looks like that conversion creates some artefacts - in these examples there are purple blotches in the uploaded file which don't exist in the original.

Probably this is because we use a low `quality` parameter in the conversion to keep the conversion time reasonable.  There may be faster conversion libraries we could use; if not then we could fork this one and add a progress indicator so that we can convert using a higher quality.

This issue might take a while depending on the options, so please check in regularly to make sure it's not getting out of control.

[heic.zip](https://github.com/Freegle/iznik-nuxt3/files/12485255/heic.zip)

**Comment by smellyshovel** [comment]
Q 0.1

Attempt 1
![Screenshot_20231005_212247](https://github.com/Freegle/iznik-nuxt3/assets/9782236/cf8e6199-4904-4234-89e5-bf24de942865)

Attemt 2
![Screenshot_20231005_212338](https://github.com/Freegle/iznik-nuxt3/assets/9782236/1b4642bc-e883-4abc-a14d-f169877e4411)

Attempt 3
![Screenshot_20231005_212413](https://github.com/Freegle/iznik-nuxt3/assets/9782236/ee323f99-1e1a-4b8a-94ba-6d368c349037)

Attempt 4
![Screenshot_20231005_212504](https://github.com/Freegle/iznik-nuxt3/assets/9782236/00731917-ca58-4dfa-b9ad-acc3c86c95be)

Attempt 5
![Screenshot_20231005_212540](https://github.com/Freegle/iznik-nuxt3/assets/9782236/10cd5359-fe3f-442d-8f7f-197e5e286260)

Q 0.5

Attempt 1
![Screenshot_20231005_212705](https://github.com/Freegle/iznik-nuxt3/assets/9782236/7efec40f-4f83-479b-a47a-c02be5293b61)

Attempt 2
![Screenshot_20231005_212747](https://github.com/Freegle/iznik-nuxt3/assets/9782236/e2d04f32-8b1e-4c96-a138-ce6b65f3f2b6)

Attempt 3
![Screenshot_20231005_212825](https://github.com/Freegle/iznik-nuxt3/assets/9782236/fcde2560-1c4d-4f06-a7cc-abb73334fa72)

Attempt 4
![Screenshot_20231005_212902](https://github.com/Freegle/iznik-nuxt3/assets/9782236/e3f52856-c434-4985-b127-43ffb250f76a)

Attempt 5
![Screenshot_20231005_212934](https://github.com/Freegle/iznik-nuxt3/assets/9782236/bade590b-3e68-4246-b370-24a0b414b707)

**Comment by smellyshovel** [comment]
You can see that there's (almost) no difference in the time it takes to convert HEIC to JPEG for the reference table close-up photo.

So, what I suggest to do. I suggest to set the quality to 0.5, bacause:
1. It solves the poor-quality-issue
2. It's recommended by the plugin's official examples

Moreover, I even suggest setting the quality to 0.92 (the plugin's default value) as per my tests it only increases the time to convert the reference photo in average by 200-300 milliseconds (which is totally acceptable if you ask me).

Regardgint the progress bar. There's already one which hides the process of converting the image and shows it as though the image is being uploaded (which is OK for the UX from my perspective: the less user know what goes under the hood, the better it is) .

**Comment by smellyshovel** [comment]
I'm gonna create a PR for this issue which sets the quality to 0.92 because that's an easy one. If you still feel like that's not a desirable desision even after my performance tests, feel free to close the PR and let me know here what steps should I take next.

**Comment by edwh** [comment]
Can you run your tests using Chrome's CPU throttling to simulate 6x slowdown?  I'd like to see the numbers from that.

**Comment by smellyshovel** [comment]
**Q 0.1**

Attempt 1
![Screenshot_20231010_144819](https://github.com/Freegle/iznik-nuxt3/assets/9782236/58e26544-ae45-4265-8f52-8aaaa2387377)

Attempt 2
![Screenshot_20231010_144954](https://github.com/Freegle/iznik-nuxt3/assets/9782236/605e9826-70e3-41ff-8f86-5e415e867599)

Attempt 3
![Screenshot_20231010_145037](https://github.com/Freegle/iznik-nuxt3/assets/9782236/a95664d8-2732-48bd-bc4d-6345786bd14e)

Attempt 4
![Screenshot_20231010_145119](https://github.com/Freegle/iznik-nuxt3/assets/9782236/44e6c6e3-4657-46c6-83bf-139ab5321f3e)

Attempt 5
![Screenshot_20231010_145200](https://github.com/Freegle/iznik-nuxt3/assets/9782236/60f4307e-5b13-45e5-8e7d-98bc5c426aae)

**Q 0.92**

Attempt 1
![Screenshot_20231010_145330](https://github.com/Freegle/iznik-nuxt3/assets/9782236/fe262fb5-8a2b-4aad-a9b9-9d2b5ddc070b)

Attempt 2
![Screenshot_20231010_145410](https://github.com/Freegle/iznik-nuxt3/assets/9782236/8070d4d0-9ec5-43a2-bd06-f0ce40b0f592)

Attempt 3
![Screenshot_20231010_145459](https://github.com/Freegle/iznik-nuxt3/assets/9782236/1d0c0d36-8861-4fe2-b4fa-8d0955929d9b)

Attempt 4
![Screenshot_20231010_145548](https://github.com/Freegle/iznik-nuxt3/assets/9782236/73221d2c-cef2-47f6-8d9a-fb68dbe13e88)

Attempt 5
![Screenshot_20231010_145627](https://github.com/Freegle/iznik-nuxt3/assets/9782236/3d6ade88-775c-4c6f-b6b0-b5be24669fcf)

**Comment by smellyshovel** [comment]
Tests with **no CPU throttling**
Q0.1 AVG 5766 ms, median 5758 ms
Q**0.5** AVG 5759 ms, median 5768 ms.

Average decreased, median inclreased. Neglectable differerence.

Tests **with CPU throttling**
Q0.1 AVG 11682 ms, median 11965 ms
Q**0.92** AVG 12829 ms, median 13158 ms.

**Increased in average by 9.80%, by the median value 9.98%.**

Also notice that when the CPU throttling was enabled, the second test used 0.92 quality (as opposed to 0.5 in the test with no CPU throttling.)
