### ISSUE TITLE
Chat not updating (?) when marking as Taken

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#20]
This may or may not be a real problem.  I marked an item as TAKEN from a Chat window (not My Posts).  The chat didn't seem to update until I refreshed.

It's possible we're not triggering the fetch of chat messages, e.g. after the outcome modal closes.

**Comment by smellyshovel** [comment]
Right after the OutcomeModal was closed:
![Screenshot_20231005_203544](https://github.com/Freegle/iznik-nuxt3/assets/9782236/336d1f9c-7d02-4b0a-9db5-443a3e303bf6)

Is that the desired behaviour? If it is, then I can't reproduce the issue.

**Comment by edwh** [comment]
Yes, that's the desired behaviour.  Thanks for testing.
