### ISSUE TITLE
Improve /unsubscribe page

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#3]
This page currently generates occasional confusion, where people:
* Don't read the warning in the blue box and click to unsubscribe
* Don't read the popup either
* Wonder why we deleted their account as they asked us to

We'd like to try forcing them to make a choice:
* Offer two options to click on, "Get fewer emails" or "Leave Freegle completely"
* If they click to get fewer emails, send them to `/settings` as an MVP.  Later we might extract the relevant components from the Settings code so that they can do that here.
* If they choose to leave completely, show the confirmation as currently.

The code is different depending on whether you are logged in or not - we need to affect and test both cases.

**Comment by smellyshovel** [comment]
A possible UI bug: when a single community is selected in the dropdown box, the text to unsubscribe entirely is there, but there's no button.

![Screenshot_20230818_161446](https://github.com/Freegle/iznik-nuxt3/assets/9782236/d28ef5a3-802e-4681-8293-00187a4b605a)

**Comment by smellyshovel** [comment]
So, what's our approach for this one? Have you gotten any ideas maybe?

**Comment by edwh** [comment]
You mean how we present it visually?  Use two buttons to give the choice.
