### ISSUE TITLE
Login and related modals rewrite

### ISSUE THREAD

**Issue by smellyshovel** [Freegle/iznik-nuxt3#41]
I'm adding the awaited `nextTick` for now, but will create a ticket for Ilia to rewrite the login (and related) modals to use the updated way of controlling them. Remember it has been skipped in the PR where we addressed all the other ones?

_Originally posted by @smellyshovel in https://github.com/Freegle/iznik-nuxt3/pull/34#discussion_r1354287852_

**Comment by smellyshovel** [comment]
@misterpekert there was the PR #32 where I rewrote the way we toggle modals in the application. However, I did not touch the login modals. And, as it turns out (see the OP), some other "login-related" modals (e.g. newUserModal) as well.

That needs to be addressed.

**Comment by edwh** [comment]
I don't think there's anything that urgently needs doing here.  We have a few modals which don't use the new pattern, but they're working ok, and there are more important things to worry about.
