### ISSUE TITLE
SpinButton refactoring

### ISSUE THREAD

**Issue by misterpekert** [Freegle/iznik-nuxt3#48]
Current implementation of SpinButton doesn't allow to flexibly control the state of SpinButton. There are 3 states:

1. Default
2. Something is in progress
3. All done

The way it's right now makes it hard to control which state you need and delays between them. We can modify internal logic a bit and it'll make life a bit easier :D 

Better to be taken after #12 is finished.

**Comment by edwh** [comment]
There's also an issue with the colour of the spinner, which means whenever we call with `variant="primary"` and `spinclass="text-white"`.  Would be better if we didn't have to specify the spinclass in that case.

**Comment by edwh** [comment]
@misterpekert Is there anything left here, now that the `handle` callback exists?

**Comment by misterpekert** [comment]
No, all done I think
