### ISSUE TITLE
Improve OutcomeModal

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#5]
When marking an OFFER as TAKEN, we ask you to select who took it from a dropdown.  The `Mark as TAKEN` button remains disabled until you do.

Disabled buttons are bad UX.  It would be better to leave the button enabled and then give the dropdown an error border, and show a message.

Also search for other disabled buttons and open another issue with a checklist to work through them.

`SpinButton` found usages:

1. [x] `OutcomeModal.vue`
2. [x] `giftaid.vue`
3. [x] `MessageEditModal.vue`
4. [x] `settings/index.vue` - *moved to another issue*

`BButton` found usages:

1. [x] `LoginModal.vue` - *moved to another issue*
2. [x] `MyMessage.vue`
3. [x] `CommunityEventModal.vue` - *upload photo indication only - won't touch*
4. [x] `StoryAddModal.vue` - *same*

**Comment by smellyshovel** [comment]
`SpinButton` found usages:

1. `OutcomeModal.vue` [*]
2. `giftaid.vue` [*]
3. `CommunityEventModal.vue` []
4. `MessageEditModal.vue` []
5. `VolunteerOpportunityModal.vue` []
6. `settings/index.vue` []

**Comment by smellyshovel** [comment]
@edwh in `CommunityEventModal.vue` the `SpinButton` is `disabled` when there's a photo being uploaded. For me that's a completely valid usage of the `disabled` attrubute. Maybe we should leave it as it is?

Anyway, it's not clear to me how to handle that any other way. Where should I add an error message if the button gets clicked when an image is being uploaded? And should we then clear the message?

**Comment by edwh** [comment]
@smellyshovel Yes, that's fine.  It's ok for something temporary where there is a visual indication that something else is going on.

**Comment by smellyshovel** [comment]
The same story for the `MessageEditModal.vue`. Though there's it's not the only case for disabling the save button. The other two are missing description and/or missing attachments. I'm leaving the disabled state for uploading the image, and adding red border for description when there's no description and no attachments. And also an error message below there.

**Comment by smellyshovel** [comment]
How should I handle the post code field in the settings?


https://github.com/Freegle/iznik-nuxt3/assets/9782236/844b715d-9bf3-4c57-ad37-6ef648fec7ab

Sometimes it shows the error message, sometimes it doesn't. Moreover, there's no indication of whether there's an error in the outside component. The only available context is whether there's something selected or not. Where should I add a message saying that it's unable to save because it's invalid? To the right of the input? Or it's better not to touch it?

**Comment by edwh** [comment]
The postcode is a slightly complex component and I need to think about it.  Exclude it from this PR and open a separate issue to consider it, please.

**Comment by smellyshovel** [comment]
@edwh What about these buttons? (Log In). I think these should remain untouched, shouldn't they?

![Screenshot_20230905_185038](https://github.com/Freegle/iznik-nuxt3/assets/9782236/5d0f3513-b017-45fb-9958-41896939e817)

**Comment by edwh** [comment]
@smellyshovel Yes, leave the login ones untouched, but open another issue.  The same thing applies that disabled is bad UX but there is already some function for spotting privacy blockers which needs consideration.

**Comment by smellyshovel** [comment]
@edwh Could you please also help me understand the flow here? It's `MyMessage.vue` component. I can see that there are 2 buttons, seems like both of them have something to do with the reposts.
The questions are:
1. What is a repost? How can I trigger it?
2. Why is the second button always disabled?
3. Should I address it in the scope of this issue somehow?

Thanks!

![Screenshot_20230905_190958](https://github.com/Freegle/iznik-nuxt3/assets/9782236/bb8234c9-6d6f-42da-916e-425cbf2ba6ba)

**Comment by smellyshovel** [comment]
@edwh Sorry, but some things are still unclear. Where to find that button exactly? Should it be in "myposts" somewhere?  I can't see it.

![Screenshot_20230905_192523](https://github.com/Freegle/iznik-nuxt3/assets/9782236/9690f913-3de6-41cb-987e-3d4d81070c87)

> Use the text currently in title as the error.

Clear, but where to show the error? Under the button? As a toast? At the top of the modal?

**Comment by smellyshovel** [comment]
OK, so, I've searched for all the `SpinButton` and `BButton` usages, took all the components where those use the `disabled` attribute and went through all of them. Some of the cases where addressed in #22, some of them where moved to separate issues and some of them are only used to block the saving of a form when there's a photo uploading. We decided not to touch anything for the last case. The only blocker now is `MyMessage.vue`; as it gets addressed, the issue can be considered resolved.

**Comment by edwh** [comment]
> @edwh Where to find that button exactly? Should it be in "myposts" somewhere? I can't see it.

You're right.  There was a bug - I had changed the API and not the client, so the button wouldn't show.  Fix pushed to master.

> > Use the text currently in title as the error.
> 
> Clear, but where to show the error? Under the button? As a toast? At the top of the modal?

Under the button.
