### ISSUE TITLE
Handle slow page transitions

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#52]
Sometimes if you're on a slow / unreliable network, then it can take a while to load the JS chunk containing the page you're navigating to.  This means you see a blank screen (with our background) for a long time.  I've seen this a few times on mobile.

What I'd like is to have the standard loader show, but only if the page transition has taken longer than 5 seconds.  This might be achievable via the Nuxt feature for page transitions, or perhaps via navigation events.

We do something a bit similar in `LayoutCommon`, but that is to handle the case where the JS doesn't run.  We could add the standard loader gif in here, and then use a `v-if` for page navigation combined with similar CSS to delay the appearance..

**Comment by untael** [comment]
Hi @edwh. I have a question. Do you want to use standard nuxt loader or your own loader (loader.gif)? I already implemented nuxt loader but I can easily change it to any other.

**Comment by edwh** [comment]
If we can use our own loader, then that would be even nicer.  Thanks.


------ Original Message ------
From "Pavel Mironov" ***@***.***>
To "Freegle/iznik-nuxt3" ***@***.***>
Cc "Edward Hibbert" ***@***.***>; "Mention" 
***@***.***>
Date 24/01/2024 02:11:02
Subject Re: [Freegle/iznik-nuxt3] Handle slow page transitions (Issue 
#52)
