### ISSUE TITLE
No action is taken when a notification is clicked

### ISSUE THREAD

**Issue by smellyshovel** [Freegle/iznik-nuxt3#6]
Not sure whether that's intentional or not, but letting you know just in case.

After the successfull registration (using a google account), there appeared a notification "Tell us about yourself!", which, I suspect, should open some certain URL when clicked, but in fact nothing happens when I click it.

![Screenshot_20230816_161427](https://github.com/Freegle/iznik-nuxt3/assets/9782236/66c8987e-aa33-471d-9799-2cf071414162)

**Comment by edwh** [comment]
Thanks - I broke this reworking to `script setup`.
