### ISSUE TITLE
Advertisement container is re-rendered whenever breakpoint changes

### ISSUE THREAD

**Issue by misterpekert** [Freegle/iznik-nuxt3#63]
There is a potential problem with the advertisement container inside the `ExternalDa` component. Its `:key` is dynamic depending on the `breakpoint`, so whenever screen width changes, it's re-rendered. We need to check if that creates any problem when an ad is inside. 

Another problem occurs when the ad is empty, after resizing div is not collapsed. Maybe we need to find a way how to tell Google that the container for the slot has been rerendered and it should reapply all the previous rules

**Comment by edwh** [comment]
Ad re-rendering is perfectly normal and is not an issue.

`ExternalDa` emits the `rendered` event which indicates whether an ad was shown.  Can you use that to collapse?

**Comment by misterpekert** [comment]
When the whole ExternalDa is destroyed, yes, it's normal. But when only that inner div -> there are no events. We don't recreate that slot; it's like nothing happened besides the ad being re-rendered. The ad doesn't load for me, so I can't check if that messes up the advertisement flow and views count.

**Comment by edwh** [comment]
> I can't check if that messes up the advertisement flow and views count.

Please don't spend time thinking about the ads - I do that.  I'd like you to focus on fixing the other issue with the sidebar height and blank spacing.

**Comment by misterpekert** [comment]
> > I can't check if that messes up the advertisement flow and views count.
> 
> 
> 
> Please don't spend time thinking about the ads - I do that.  I'd like you to focus on fixing the other issue with the sidebar height and blank spacing.

That was fixed in the PR

**Comment by edwh** [comment]
Great. So we can close this one?
