### ISSUE TITLE
Auto-suggest of addresses

### ISSUE THREAD

**Issue by edwh** [Freegle/iznik-nuxt3#69]
I've recently implemented some function for Chat which spots when you are typing a postal address and suggests it:

![image](https://github.com/Freegle/iznik-nuxt3/assets/56696/487992f8-4575-4097-b245-95d48b44b0d6)

This works by:

- checking if we know the user's postcode
- querying the server for the list of postal addresses in that postcode
- spotting when you start typing one of them
- showing a suggestion

I've experimented with various ways of showing this to the user:

1. Via `Popper` (the current approach).  This gets very low interaction.  I would guess that is because it is outside the textbox and therefore some people won't even see it.
2. Via a popup modal.  This gets a lot more interaction (as you would expect), but more cancels than people accepting it.  Some of this may be that people react to interrupting popups by closing them reflexively.  Popups are annoying.

I'd like to try an approach which looks like standard autocomplete, so that the suggestion was just the address (without any text) and was shown right next to the cursor.  Then people would see it.  If they don't select it, but typing the exact same match then we should treat that as a selection.

Can you find a way to implement that?

**Comment by untael** [comment]
Hi @edwh. I started to investigate that feature and I have a question:

What do you mean by `standard autocomplete`:

1. 
![image](https://github.com/Freegle/iznik-nuxt3/assets/11652328/53ef9116-f2fe-4702-b100-9d0694d84ccf)
Selected text when you start typing something in browser input?

2. Default HTML autocomplete behaviour https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete

3. Dropdown autocomplete

**Comment by untael** [comment]
Also I think we can improve algorythm of address comparing by using something like https://www.npmjs.com/package/string-similarity which uses https://en.wikipedia.org/wiki/Levenshtein_distance under the hood.

**Comment by edwh** [comment]
> What do you mean by `standard autocomplete`:

I suggest using the same library that ChitChat uses for @.  

> Also I think we can improve algorithm of address

I thought about that - we use Damerau-Levenshtein in some places.  But most addresses in the UK start with a house number, and house numbers are very close in terms of that distance.  If you start typing "11" and it suggests addresses starting with 11, 12, 13, 14, 15 etc then it just looks silly.  I think that an approximate match would result in more irritating suggestions than any benefit.
