### ISSUE TITLE
"When could you collect?" better as multiline

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt3#84]
When responding to an offer, as well as the general reply textbox, recently there is now a separate "When could you collect?" field. Please could that field be made multiline, like the "Your reply" field? That would make it easier when typing more a few words.

(I couldn't find the text "When could you collect?" when searching GitHub, so I hope this is the right repo!)

**Comment by JohnVeness** [comment]
Thanks for the reply. I can understand you wanting to keep replies brief.

The current single line does make it hard to use, especially (as you say) on mobile, where it's hard enough to move a cursor to edit previous words, and even harder when the thing you want to edit is off the screen. I like what Google has done recently for its search box, which appears as a single-line initially, but turns into multiple lines if you overflow it as you type. That way it's easy to just tap on the screen to move the cursor to anywhere in the previously-typed text. But a two line box would be better than the current one line.

Another problem I've discovered with the current single-line is that if you press return (this was on desktop) while in that line, it cancels the message! I didn't realise this until I wondered why I had no reply after a while :(. I had pressed return because I wanted to "sign off" the message with my name on a separate line - which is another reason I'd like it to be a multi-line box! I had assumed that pressing return in that text box had sent the message.

**Comment by edwh** [comment]
I like auto-resize textboxes too.  The package we're using for visual components doesn't yet support that, unfortunately - see Auto-height on https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/components/form-textarea.html.  I'll set it to 2 rows.

There's no need to sign off in the collection times box - that's exactly the kind of thing I want to keep out of that box by keeping it short, because it's nothing to do with collection times.  In due course we might be able to interpret the text people put in there, but we won't be able to do that if it's cluttered up with other stuff.

I can't reproduce the cancel thing you describe, but let's see what happens now that it's a textarea.  That'll be live in a few minutes.

**Comment by JohnVeness** [comment]
Thanks Edward. At the moment, I sign off in the general reply box above, so that's OK. I was just explaining why I had pressed return in the collection times box!

I'll try the new version when I next have a post that I wish to reply to, which may be some time. Unless you have a sandbox version for testing?

**Comment by JohnVeness** [comment]
Ah, thanks for the FreeglePlayground link, that will be useful for various things in future.

Unfortunately there are currently no OFFERs in there that I can test a reply to. And I can't reply to my own offers! I guess I could setup a new account...

**Comment by edwh** [comment]
Yes, having a couple of accounts is useful for testing.


------ Original Message ------
From "John Veness" ***@***.***>
To "Freegle/iznik-nuxt3" ***@***.***>
Cc "Edward Hibbert" ***@***.***>; "Comment" 
***@***.***>
Date 12/04/2024 15:23:15
Subject Re: [Freegle/iznik-nuxt3] "When could you collect?" better as 
multiline (Issue #84)

**Comment by JohnVeness** [comment]
For info, the "pressing return in that field cancelled the message" issue is no longer the case now this is a textarea. Many thanks :)

**Comment by JohnVeness** [comment]
I think this can be closed now. Thank you!

**Comment by edwh** [comment]
Ah yes. Thanks.
