### ISSUE TITLE
No "Hide chat" button for a deleted user

### ISSUE THREAD

**Issue by JohnVeness** [Freegle/iznik-nuxt3#94]
I have a chat with a user that was deleted. The only button visible in the chat header is Block. In particular, there's no "Hide chat" button, which I wanted to do.
![image](https://github.com/Freegle/iznik-nuxt3/assets/2512915/b56aada9-dc47-4860-ba42-a13aa53ae928)

**Comment by edwh** [comment]
You're right, it doesn't show that button.  I can't think why it shouldn't, so I've made that change.
